name: ounce
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.0
  intl_phone_number_input: ^0.7.4
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  firebase_analytics: ^11.4.4
  flutter_local_notifications: ^19.0.0
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.4
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ounce.png"

flutter_native_splash:
  background_image: assets/images/black.png
  image: assets/images/gold.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: fill
  fullscreen: true
  android_12:
    color: "#2E2E2E"
    image: assets/images/gold.png
    android_gravity: fill
    fullscreen: true

flutter:
  generate: true
  assets:
    - assets/icons/
    - assets/images/
    - lib/l10n/
  uses-material-design: true

flutter_intl:
  enabled: true