name: ounce
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.0
  intl_phone_number_input: ^0.7.4
  http: ^1.2.1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.3
  http_parser: ^4.0.2
  path: ^1.9.0
  mime: ^1.0.5
  sizer: ^2.0.15
  firebase_core: ^2.31.1
  firebase_messaging: ^14.9.3
  flutter_local_notifications: ^17.1.2
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.0.7
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ounce.png"

flutter_native_splash:
  color: "#ffffff" # Background color
  image: assets/images/backgroundounce.png
  background_image: assets/images/backgroundounce.png
  android: true
  ios: true

flutter:
  generate: true
  assets:
    - assets/icons/
    - assets/images/
    - lib/l10n/
  uses-material-design: true

flutter_intl:
  enabled: true